name: speed_test_app

services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/app.dockerfile

    ports:
      - "8000:80"

    volumes:
      - C:/workspaces/speed_test/config:/config

      # Keep frontend files live-mounted during development.
      - C:/workspaces/speed_test/web_page:/app/static:ro

    restart: unless-stopped
